name: "Run: Generate documentation (docker hub)"
description: "Generate documentation (docker hub)"

permissions: {}

inputs:
  work_dir:
    description: "Working directory"
    default: "/github/workspace"
  script:
    description: "Run script"
    default: "./_actions/src/generate-docs.sh"
  in_dir:
    description: "Source directory"
    required: true
  out_dir:
    description: "Destination directory"
    required: true

runs:
  using: docker
  image: docker://docker.io/antirs/shwrap:generate-docs
  args:
    - "${{ inputs.work_dir }}"
    - "${{ inputs.script }}"
    - "${{ inputs.in_dir }}"
    - "${{ inputs.out_dir }}"
  env:
    GH_MODE: 1
