name: "Run: Build documentation"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-doc-${{ github.run_id }}"
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "doc/**"
      - ".github/workflows/doc.yml"
  push:
    paths:
      - "doc/**"
      - ".github/workflows/doc.yml"
  schedule:
    - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  doc:
    permissions:
      contents: write
    concurrency:
      group: "doc-${{ inputs.run_id }}"
      cancel-in-progress: true
    uses: ekotik/sh.wrap/.github/workflows/actions-hub.yml@actions
    with:
      run_id: "doc/actions"
      script_hugo_site: "./_actions/src/docsy-site.sh"
      in_dir: "./src"
      out_cache: "devdoc-${{ github.run_id }}"
      devdocs_repo: "https://github.com/ekotik/sh.wrap"
      devdocs_branch: "devdocs"
      devdocs_tag: "v0.0.1-devdocs"
      docs_dir: "./doc/content"
      site_dir: "./doc"
      public_dir: "./public"
      public_cache: "doc-${{ github.run_id }}"
      gh_pages_repo: "https://github.com/ekotik/sh.wrap"
      gh_pages_branch: "gh-pages/sh.wrap"
