name: "Run: Git tasks (hub)"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-git-tasks-hub-${{ github.run_id }}-${{ inputs.run_id }}"
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      run_id:
        description: "Run ID"
        type: string
        required: true
      work_dir:
        description: "Working directory"
        type: string
        default: "/github/workspace"
      script:
        description: "Run script"
        type: string
        default: "./_actions/src/git-tasks.sh"
      gh_bin:
        description: "gh binary (docker)"
        type: string
        default: "/go/gh"
      git_repo:
        description: "Git repository"
        type: string
        required: true
      git_branch:
        description: "Git branch"
        type: string
        required: true
      git_commands:
        description: "Git comands"
        type: string
        default: "git status"

env:
  RUN_ID: "${{ inputs.run_id }}"
  WORK_DIR: "${{ inputs.work_dir }}"
  SCRIPT: "${{ inputs.script }}"
  GH_BIN: "${{ inputs.gh_bin }}"
  GIT_REPO: "${{ inputs.git_repo }}"
  GIT_BRANCH: "${{ inputs.git_branch }}"
  GIT_COMMANDS: "${{ inputs.git_commands }}"

jobs:
  tasks:
    concurrency:
      group: "git-tasks-hub/tasks-${{ inputs.run_id }}"
      cancel-in-progress: true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Checkout actions"
        uses: ekotik/sh.wrap@actions
      - name: "Git tasks"
        uses: ./_actions/.github/actions/git-tasks-hub
        with:
          work_dir: "${{ inputs.work_dir }}"
          script: "${{ inputs.script }}"
          gh_bin: "${{ inputs.gh_bin }}"
          git_repo: "${{ inputs.git_repo }}"
          git_branch: "${{ inputs.git_branch }}"
          git_commands: "${{ inputs.git_commands }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
