name: "Run: Build hugo site"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-hugo-site-${{ github.run_id }}-${{ inputs.run_id }}"
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      run_id:
        description: "Run ID"
        type: string
        required: true
      dockerfile_template:
        description: "Dockerfile template file"
        type: string
        default: "./_actions/docker/hugo-site.Dockerfile"
      dockerfile:
        description: "Dockerfile to build and run"
        type: string
        default: "hugo-site.Dockerfile"
      work_dir:
        description: "Working directory"
        type: string
        default: "/github/workspace"
      script:
        description: "Run script"
        type: string
        default: "./_actions/src/hugo-site.sh"
      hugo_bin_source:
        description: "hugo binary (host)"
        type: string
        default: "./hugo/hugo"
      hugo_bin_dest:
        description: "hugo binary (docker)"
        type: string
        default: "/go/hugo"
      hugo_bin_path:
        description: "hugo binary directory (host)"
        type: string
        default: "./hugo"
      hugo_repo:
        description: "hugo repository"
        type: string
        default: "https://github.com/gohugoio/hugo"
      hugo_hash:
        description: "hugo repository commit"
        type: string
        default: "bfebd8c02cfc0d4e4786e0f64932d832d3976e92"
      hugo_build_args:
        description: "hugo build arguments"
        type: string
        default: ""
      docs_dir:
        description: "Documentation directory"
        type: string
        default: "./doc"
      site_dir:
        description: "Site directory"
        type: string
        default: "./doc/site"
      public_dir:
        description: "Publish directory"
        type: string
        default: "./public"
      public_cache:
        description: "Publish cache"
        type: string
        default: "hugo-site"

env:
  DOCKERFILE_SCRIPTS_PATH: "./_actions/src"
  RUN_ID: "${{ inputs.run_id }}"
  DOCKERFILE_TEMPLATE: "${{ inputs.dockerfile_template }}"
  DOCKERFILE: "${{ inputs.dockerfile }}"
  WORK_DIR: "${{ inputs.work_dir }}"
  SCRIPT: "${{ inputs.script }}"
  HUGO_BIN_SOURCE: "${{ inputs.hugo_bin_source }}"
  HUGO_BIN_DEST: "${{ inputs.hugo_bin_dest }}"
  HUGO_BIN_PATH: "${{ inputs.hugo_bin_path }}"
  HUGO_REPO: "${{ inputs.hugo_repo }}"
  HUGO_HASH: "${{ inputs.hugo_hash }}"
  HUGO_BUILD_ARGS: "${{ inputs.hugo_build_args }}"
  DOCS_DIR: "${{ inputs.docs_dir }}"
  SITE_DIR: "${{ inputs.site_dir }}"
  PUBLIC_DIR: "${{ inputs.public_dir }}"
  PUBLIC_CACHE: "${{ inputs.public_cache }}"

jobs:
  hugo-build:
    concurrency:
      group: "hugo-site/hugo-build-${{ inputs.run_id }}"
      cancel-in-progress: true
    uses: ekotik/sh.wrap/.github/workflows/go-build.yml@v0.0.0-actions
    with:
      run_id: "hugo-site/hugo-build-${{ inputs.run_id }}"
      dockerfile_template: "./_actions/docker/go-build.Dockerfile"
      dockerfile: "./go-build.Dockerfile"
      git_repo: "${{ inputs.hugo_repo }}"
      git_hash: "${{ inputs.hugo_hash }}"
      build_args: "${{ inputs.hugo_build_args }}"
      go_bin: "${{ inputs.hugo_bin_source }}"
      use_cache: true
  hugo-site:
    concurrency:
      group: "hugo-site/hugo-site-${{ inputs.run_id }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs:
      - hugo-build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Checkout actions"
        uses: ekotik/sh.wrap@v0.0.0-actions
      - name: "Retrieve hugo binary cache"
        uses: actions/cache@v3
        with:
          path: "${{ inputs.hugo_bin_source }}"
          key: "${{ runner.os }}-go-build-${{ inputs.hugo_hash }}-${{ inputs.hugo_build_args }}"
      - uses: ./_actions/.github/actions/prepare-dockerfile
      - name: "Build hugo site"
        uses: ./_actions/.github/actions/hugo-site
        with:
          script: "${{ inputs.script }}"
          hugo_bin: "${{ inputs.hugo_bin_dest }}"
          docs_dir: "${{ inputs.docs_dir }}"
          site_dir: "${{ inputs.site_dir }}"
          public_dir: "${{ inputs.public_dir }}"
      - name: "Archive hugo site"
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.public_cache }}"
          path: "${{ inputs.public_dir }}"
