name: "Test: Convert documentation (workflow)"
run-name: "Test: Convert documentation - ${{ inputs.run_id }}"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-pandoc-convert-test-${{ github.run_id }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID"
        type: string
        required: true
      payload:
        description: "Inputs payload"
        type: string
        required: true

jobs:
  pandoc-convert-test:
    concurrency:
      group: "pandoc-convert-test-${{ inputs.run_id }}"
      cancel-in-progress: true
    uses: ekotik/sh.wrap/.github/workflows/pandoc-convert.yml@actions
    with:
      run_id: "${{ inputs.run_id }}"
      dockerfile_template: "${{ fromJson(inputs.payload).dockerfile_template }}"
      dockerfile: "${{ fromJson(inputs.payload).dockerfile }}"
      work_dir: "${{ fromJson(inputs.payload).work_dir }}"
      script: "${{ fromJson(inputs.payload).script }}"
      in_dir: "${{ fromJson(inputs.payload).in_dir }}"
      out_dir: "${{ fromJson(inputs.payload).out_dir }}"
      pandoc_clean: "${{ fromJson(inputs.payload).pandoc_clean }}"
      out_cache: "${{ fromJson(inputs.payload).out_cache }}"
      out_cache_dir: "${{ fromJson(inputs.payload).out_cache_dir }}"
