name: "Run: Test shellcheck"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-${{ github.run_id }}"
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "**.sh"
      - ".github/workflows/test.yml"
  push:
    paths:
      - "**.sh"
      - ".github/workflows/test.yml"

jobs:
  test:
    concurrency:
      group: "test-${{ github.ref }}"
      cancel-in-progress: true
    uses: ekotik/sh.wrap/.github/workflows/test-shellcheck.yml@actions
    with:
      run_id: "test-shellcheck-test-${{ github.ref }}"
      dirs: "./src\n./test"
