name: Test shellcheck

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: {}

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - '**.sh'
  push:
    paths:
      - '**.sh'

jobs:
  test-shellcheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ekotik/sh.wrap@actions-shellcheck
        with:
          script: "test/tests.sh"
