name: "Run: Test shellcheck"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-${{ github.run_id }}"
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "**.sh"
      - ".github/workflows/test.yml"
  push:
    paths:
      - "**.sh"
      - ".github/workflows/test.yml"

jobs:
  test-shellcheck:
    concurrency:
      group: "test/test-shellcheck-${{ github.ref }}"
      cancel-in-progress: true
    uses: ekotik/sh.wrap/.github/workflows/test-shellcheck-hub.yml@actions
    with:
      run_id: "test-shellcheck-test-${{ github.ref }}"
      dirs: "./src\n./test"
  test-runner:
    strategy:
      matrix:
        bash_version: ["5.2", "5.1", "5.0", "4.4"]
    concurrency:
      group: "test/test-runner-${{ matrix.bash_version }}-${{ github.ref }}"
      cancel-in-progress: false
    uses: ekotik/sh.wrap/.github/workflows/test-runner.yml@actions
    with:
      run_id: "test-shellcheck-test-${{ matrix.bash_version }}-${{ github.ref }}"
      bash_docker_version: "${{ matrix.bash_version }}"
      microspec_args: "./test/*.spec.sh"
