name: "Test: shellcheck (hub)"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-shellcheck-hub-${{ github.run_id }}-${{ inputs.run_id }}"
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      run_id:
        description: "Run ID"
        type: string
        required: true
      work_dir:
        description: "Working directory"
        type: string
        default: "/github/workspace"
      script:
        description: "Run script"
        type: string
        default: "./_actions/src/test-shellcheck.sh"
      dirs:
        description: "Source directories"
        type: string
        default: "./_actions/src"

env:
  RUN_ID: "${{ inputs.run_id }}"
  WORK_DIR: "${{ inputs.work_dir }}"
  SCRIPT: "${{ inputs.script }}"
  DIRS: "${{ inputs.dirs }}"

jobs:
  test-shellcheck:
    concurrency:
      group: "test-shellcheck-hub-${{ inputs.run_id }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Checkout actions"
        uses: ekotik/sh.wrap@actions
      - uses: ./_actions/.github/actions/test-shellcheck-hub
        with:
          work_dir: "${{ inputs.work_dir }}"
          script: "${{ inputs.script }}"
          dirs: "${{ inputs.dirs }}"
