name: "Run: Update git submodules (hub)"

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-update-submodules-hub-${{ github.run_id }}-${{ inputs.run_id }}"
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      run_id:
        description: "Run ID"
        type: string
        required: true
      work_dir:
        description: "Working directory"
        type: string
        default: "/github/workspace"
      script:
        description: "Run script"
        type: string
        default: "./_actions/src/update-submodules.sh"
      gh_bin:
        description: "gh binary (docker)"
        type: string
        default: "/go/gh"
      git_repo:
        description: "Git repository"
        type: string
        required: true
      git_branch:
        description: "Git repository branch"
        type: string
        default: true
      git_repo_dir:
        description: "Git repository directory"
        type: string
        required: true
      git_amend:
        description: "Git amend commit"
        type: string
        default: ""

env:
  RUN_ID: "${{ inputs.run_id }}"
  WORK_DIR: "${{ inputs.work_dir }}"
  SCRIPT: "${{ inputs.script }}"
  GH_BIN: "${{ inputs.gh_bin }}"
  GIT_REPO: "${{ inputs.git_repo }}"
  GIT_BRANCH: "${{ inputs.git_branch }}"
  GIT_REPO_DIR: "${{ inputs.git_repo_dir }}"
  GIT_AMEND: "${{ inputs.git_amend }}"

jobs:
  update-submodules:
    concurrency:
      group: "update-submodules-hub/update-submodules-${{ inputs.run_id }}"
      cancel-in-progress: true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Checkout actions"
        uses: ekotik/sh.wrap@actions
      - name: "Update git submodules"
        uses: ./_actions/.github/actions/update-submodules-hub
        with:
          work_dir: "${{ inputs.work_dir }}"
          script: "${{ inputs.script }}"
          gh_bin: "${{ inputs.gh_bin }}"
          git_repo: "${{ inputs.git_repo }}"
          git_branch: "${{ inputs.git_branch }}"
          git_repo_dir: "${{ inputs.git_repo_dir }}"
          git_amend: "${{ inputs.git_amend }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
